name: frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  firebase_messaging: ^14.6.2
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  http: ^0.13.5
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_stripe: ^5.0.0
  flutter_dotenv: ^5.0.2
  permission_handler: ^10.3.0
  mailer: ^6.0.1
  shared_preferences: ^2.1.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  # flutter packages pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/logo-app.png"
  adaptive_icon_background: "images/logo-app.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/.env

  fonts:
    - family: NunitoSans_10pt
      fonts:
        - asset: fonts/NunitoSans_10pt-Regular.ttf
          weight: 300
        - asset: fonts/NunitoSans_10pt-Bold.ttf
          weight: 700
